import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { McLaren } from "next/font/google";
import SecurityBlocker from "@/components/securityBlocker";

const mcLaren = McLaren({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create New",
  description: "Generated by Ajeet Sharma",
  icons: {
    icon: "/favicon.ico.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.png" type="image/png" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${mcLaren.className} antialiased mclaren-font bg-[#002c2f]`}
      >
        <SecurityBlocker />
        {children}
      </body>
    </html>
  );
}
